import json, glob, os

HEADER = "<!-- GENERATED from content/modules/{mid}.json - edit the canonical module, not this file. -->\n"

def gen_runbook(m):
    lines = []
    lines.append(HEADER.format(mid=m['id']))
    lines.append('# Mentor Run-Sheet: ' + m['title'])
    lines.append('')
    lines.append('**Module:** `' + m['id'] + '` (rev ' + str(m['revision']) + ', status: ' + m['status'] + ')  ')
    lines.append('**Ages:** ' + str(m['ageBand']['min']) + '-' + str(m['ageBand']['max']) + ' (target ~' + str(m['ageBand']['target']) + ')  ')
    lines.append('**Duration:** ' + str(m['durationMinutes']['min']) + '-' + str(m['durationMinutes']['max']) + ' min  ')
    lines.append('**Edition:** ' + ', '.join(m['editions']).title() + ' | **Input:** ' + ', '.join(m['inputMethods']) + '  ')
    lines.append('**Delivery:** ' + ', '.join(m['deliveryModes']))
    lines.append('')
    lines.append('## Preparation')
    lines.append('')
    lines.append('### Guardian setup')
    for s in m['setup']['guardianSteps']: lines.append('- ' + s)
    lines.append('')
    lines.append('### Mentor preflight')
    for s in m['setup']['mentorPreflight']: lines.append('- ' + s)
    lines.append('')
    if m.get('worldSpecification'):
        ws = m['worldSpecification']
        lines.append('### World spec (' + ws['mode'] + ')')
        lines.append(ws['description'])
        lines.append('')
    lines.append('## Quick Win')
    qw = next((f for f in m['flow'] if f['phase'].lower().startswith('quick')), None)
    lines.append(qw['childAction'] if qw else 'See flow below.')
    lines.append('')
    lines.append('## Session Flow')
    lines.append('')
    lines.append('| Phase | Min | You do | Child does |')
    lines.append('|---|---|---|---|')
    for f in m['flow']: lines.append('| ' + f['phase'] + ' | ' + f['minutes'] + ' | ' + '; '.join(f['mentorMoves']) + ' | ' + f['childAction'] + ' |')
    lines.append('')
    lines.append('## Script Starters')
    lines.append('')
    for s in m['mentorScript']['openingLines']: lines.append('> "' + s + '"')
    lines.append('')
    lines.append('**Key phrases:**')
    for s in m['mentorScript']['keyPhrases']: lines.append('- "' + s + '"')
    lines.append('')
    lines.append('## Shared Roles')
    lines.append('')
    lines.append('- **Child (' + m['sharedRoles']['childRole'] + '):** primary maker and decision-maker')
    lines.append('- **Mentor (' + m['sharedRoles']['mentorRole'] + '):** support only')
    lines.append('- **Rotation:** ' + m['sharedRoles']['rotationNotes'])
    lines.append('')
    lines.append('## Choice Points')
    lines.append('')
    for c in m['childChoicePoints']: lines.append('- **' + c['prompt'] + '** -> ' + ' / '.join(c['options']))
    lines.append('')
    lines.append('## Hint Ladder (one at a time!)')
    lines.append('')
    for i, h in enumerate(m['hintLadder'], 1): lines.append(str(i) + '. "' + h + '"')
    lines.append('')
    lines.append('## Common Problems')
    lines.append('')
    lines.append('| Problem | Fix |')
    lines.append('|---|---|')
    for p in m['commonProblems']: lines.append('| ' + p['problem'] + ' | ' + p['fix'] + ' |')
    lines.append('')
    lines.append('## Recovery / Reset')
    lines.append('')
    lines.append(m['resetPath'])
    lines.append('')
    lines.append('## Solo Fallback (multiplayer fails)')
    lines.append('')
    lines.append(m['soloFallback'])
    lines.append('')
    lines.append('## Evidence Options')
    lines.append(', '.join(m['evidenceOptions']))
    lines.append('')
    lines.append('## Safety Notes')
    lines.append('')
    for s in m['safetyRequirements']: lines.append('- ' + s)
    lines.append('')
    lines.append('## Parent Summary Template')
    lines.append('')
    lines.append('> ' + m['parentSummaryTemplate'])
    lines.append('')
    lines.append('## Next Modules')
    lines.append(', '.join('`' + n + '`' for n in m['nextModules']))
    lines.append('')
    pt = '**NOT yet human-playtested**' if not m['review']['playtested'] else 'Human-playtested'
    lines.append('*Review status: ' + pt + '. Last reviewed ' + m['review']['lastReviewed'] + '. ' + m['review']['notes'] + '*')
    return '\n'.join(lines)

def gen_quest(m):
    cues = '\n'.join(str(i) + '. ' + c['cueText'] + ' _(then: ' + c['action'] + ')_' for i, c in enumerate(m['learnerCues'], 1))
    choices = '\n'.join('- ' + c['prompt'] + '\n  - ' + '\n  - '.join(c['options']) for c in m['childChoicePoints'])
    body = '# ' + m['shortChildTitle'] + '!\n\n' + m['outcome'] + '\n\n## Your Steps\n\n' + cues + '\n\n## Fun Choices\n\n' + choices + '\n\nShow your grown-up what you made today!\n'
    return HEADER.format(mid=m['id']) + body

for f in sorted(glob.glob('content/modules/**/*.json', recursive=True)):
    m = json.load(open(f, encoding='utf-8'))
    rb = gen_runbook(m)
    os.makedirs('content/pathways', exist_ok=True)
    open(os.path.join('content/pathways', m['id'] + '-runbook.md'), 'w', encoding='utf-8').write(rb + '\n')
    qd = os.path.dirname(f)
    open(os.path.join(qd, m['id'] + '-quest-card.md'), 'w', encoding='utf-8').write(gen_quest(m) + '\n')

print('generated runbooks and quest cards')
